apiVersion: v1
kind: Service
metadata:
  namespace: student
  labels:
    app: student-api
  name: student-api
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
    # - name: grpc
    #   port: 5002
    #   protocol: TCP
    #   targetPort: 5002
  selector:
    app: student-api
  type: LoadBalancer
